/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function adversarialValidate(proposal: string, baselineHandle: string, candidateHandle?: string | undefined | null, options?: string | undefined | null): string

/** Analyze a Pi tool input through the native registry. */
export declare function analyzeTool(toolName: string, input: string): string

export declare function buildCorpusModel(corpus: string, handle: string, options?: string | undefined | null): string

export declare function classifyMutationTrustBoundary(path: string | undefined | null, context: string): string

export declare function classifyOverlap(left: string, right: string): string

export declare function classifyPathFact(input: string, context: string): string

export declare function classifyStageEffect(stage: string): string

export declare function compileMatch(matcher: string): string

/**
 * Parse a bash command and return the generated contract as JSON. Keeping the
 * binding JSON-shaped avoids exposing tree-sitter or napi-owned object types.
 */
export declare function compilePack(pack: string): string

export declare function compilePackMetadata(metadata: string): string

export declare function compilePolicy(policy: string): string

export declare function composePolicy(request: string): string

export declare function createPolicy(policy: string): string

export declare function decide(handle: string, shape: string): string

export declare function decideBatch(handle: string, shapes: string): string

export declare function effectRegistry(): string

export declare function enrichPathFacts(shape: string, context: string): string

export declare function freePolicy(handle: string): boolean

export declare function health(): HealthInfo

export interface HealthInfo {
  version: string
  grammarVersion: string
  target: string
}

export declare function match(matcher: string, shape: string): boolean

export declare function parseBash(command: string): string

export declare function reduceForLoopIterator(stage: string, effectiveCwd: string, context: string, home?: string | undefined | null): string

export declare function reduceIteratorEntry(entry: string, effectiveCwd: string, context: string, home?: string | undefined | null): string

export declare function replayDelta(corpus: string, baselineHandle: string, candidateHandle: string, options?: string | undefined | null): string

export declare function stageFileInputIndices(stage: string): string

export declare function validateCompoundAllowCanonicality(expr: string): string

export declare function validatePackAgainstFloor(request: string): string
