// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdversarialCaseCategory =
  | "path-scope"
  | "quoting"
  | "substitution"
  | "redirect"
  | "operator"
  | "pipeline"
  | "cwd-prefix"
  | "program-specific"
  | "parser-footgun";
