// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdversarialCase } from "./AdversarialCase.ts";
import type { AdversarialCaseResult } from "./AdversarialCaseResult.ts";
import type { AdversarialValidationStatus } from "./AdversarialValidationStatus.ts";
import type { ProposalNotRunReason } from "./ProposalNotRunReason.ts";

export type AdversarialValidationReport = {
  version: number;
  proposalId: string;
  status: AdversarialValidationStatus;
  notRun?: ProposalNotRunReason;
  generatedCaseCount: number;
  evaluatedCaseCount: number;
  failedCaseCount: number;
  skippedCaseCount: number;
  cases: ReadonlyArray<AdversarialCase>;
  results: ReadonlyArray<AdversarialCaseResult>;
  warnings: ReadonlyArray<string>;
};
