// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdversarialCaseCategory } from "./AdversarialCaseCategory.ts";
import type { AdversarialCaseExpectation } from "./AdversarialCaseExpectation.ts";
import type { AdversarialCaseResultOutcome } from "./AdversarialCaseResultOutcome.ts";
import type { ReplayStatus } from "./ReplayStatus.ts";

export type AdversarialCaseResult = {
  caseId: string;
  command: string;
  category: AdversarialCaseCategory;
  expectation: AdversarialCaseExpectation;
  outcome: AdversarialCaseResultOutcome;
  actualStatus?: ReplayStatus;
  actualRuleId?: string;
  actualReason?: string;
  diagnostics: ReadonlyArray<string>;
};
