// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdversarialCaseCategory } from "./AdversarialCaseCategory.ts";
import type { AdversarialCaseExpectation } from "./AdversarialCaseExpectation.ts";
import type { AdversarialCaseSource } from "./AdversarialCaseSource.ts";

export type AdversarialCase = {
  id: string;
  command: string;
  category: AdversarialCaseCategory;
  expectation: AdversarialCaseExpectation;
  rationale: string;
  source: AdversarialCaseSource;
  derivedFrom?: string;
};
