// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathFactProjectScope } from "./PathFactProjectScope.ts";

export type BashPathFactContext = {
  cwd: string;
  projectScope: PathFactProjectScope;
  homeDirectory?: string;
  systemPathPrefixes?: ReadonlyArray<string>;
};
