// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashPathFactProvenanceEntry } from "./BashPathFactProvenanceEntry.ts";
import type { IteratorSourceKind } from "./IteratorSourceKind.ts";
import type { LoopVariableUnknownReason } from "./LoopVariableUnknownReason.ts";

export type BashPathFactProvenance = {
  kind: "loop-variable";
  variableName: string;
  iteratorSourceKind: IteratorSourceKind;
  iteratorEntries: ReadonlyArray<BashPathFactProvenanceEntry>;
  loopStageIndex: number;
  unknownReason?: LoopVariableUnknownReason;
};
