// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceSpan } from "./SourceSpan.ts";

export type BashForLoopKeywordSpans = {
  for?: SourceSpan;
  in?: SourceSpan;
  do?: SourceSpan;
  done?: SourceSpan;
};
