// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathScope } from "./PathScope.ts";
import type { PathUnknownReason } from "./PathUnknownReason.ts";
import type { QuoteKind } from "./QuoteKind.ts";

export type BashPathFactProvenanceEntry = {
  raw: string;
  literal?: string;
  concreteAbsolutePath?: string;
  staticPrefixAbsolutePath?: string;
  scope: PathScope;
  matchedScopes: ReadonlyArray<PathScope>;
  quote: QuoteKind;
  unknownReason?: PathUnknownReason;
};
