// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashFlag } from "./BashFlag.ts";
import type { BashLoopVariableReference } from "./BashLoopVariableReference.ts";
import type { EnvironmentAssignment } from "./EnvironmentAssignment.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashStageProgram = {
  program: string;
  resolvable: boolean;
  arguments: ReadonlyArray<string>;
  flags: ReadonlyArray<BashFlag>;
  environment: ReadonlyArray<EnvironmentAssignment>;
  variableReferences?: ReadonlyArray<BashLoopVariableReference>;
  span: SourceSpan;
};
