// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoopQuoteKind } from "./LoopQuoteKind.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashLoopVariableReference = {
  name: string;
  raw: string;
  quote: LoopQuoteKind;
  span: SourceSpan;
};
