// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashStage } from "./BashStage.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashPipeline = {
  stages: ReadonlyArray<BashStage>;
  pipeTargets: ReadonlyArray<string>;
  span: SourceSpan;
};
