// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashBlock } from "./BashBlock.ts";
import type { BashConditionalArm } from "./BashConditionalArm.ts";
import type { BashControlConstruct } from "./BashControlConstruct.ts";
import type { BashForLoopKeywordSpans } from "./BashForLoopKeywordSpans.ts";
import type { BashIteratorEntry } from "./BashIteratorEntry.ts";
import type { BashStageProgram } from "./BashStageProgram.ts";
import type { Redirect } from "./Redirect.ts";
import type { SourceSpan } from "./SourceSpan.ts";
import type { Substitution } from "./Substitution.ts";

export type BashStage =
  | {
      kind: "command";
      program: BashStageProgram;
      substitutions: ReadonlyArray<Substitution>;
      redirects: ReadonlyArray<Redirect>;
      span: SourceSpan;
    }
  | { kind: "subshell"; span: SourceSpan }
  | { kind: "control-flow"; construct: BashControlConstruct; span: SourceSpan }
  | {
      kind: "for-loop";
      variable: string;
      variableSpan: SourceSpan;
      iterator: ReadonlyArray<BashIteratorEntry>;
      body: BashBlock;
      keywordSpans: BashForLoopKeywordSpans;
      span: SourceSpan;
    }
  | {
      kind: "brace-group";
      body: BashBlock;
      redirects: ReadonlyArray<Redirect>;
      span: SourceSpan;
    }
  | {
      kind: "conditional";
      arms: ReadonlyArray<BashConditionalArm>;
      elseBody?: BashBlock;
      elseSpan?: SourceSpan;
      span: SourceSpan;
    }
  | { kind: "unsupported"; reason: string; span: SourceSpan };
