// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashPathFactProvenance } from "./BashPathFactProvenance.ts";
import type { PathAccess } from "./PathAccess.ts";
import type { PathNormalization } from "./PathNormalization.ts";
import type { PathScope } from "./PathScope.ts";
import type { PathUnknownReason } from "./PathUnknownReason.ts";
import type { PathUsageKind } from "./PathUsageKind.ts";
import type { QuoteKind } from "./QuoteKind.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashPathFact = {
  id: string;
  stageIndex?: number;
  program?: string;
  usage: PathUsageKind;
  access: PathAccess;
  raw: string;
  literal?: string;
  absolutePath?: string;
  scope: PathScope;
  matchedScopes: ReadonlyArray<PathScope>;
  normalization: PathNormalization;
  isAbsolute: boolean;
  isRelative: boolean;
  hasParentTraversal: boolean;
  quote: QuoteKind;
  dynamic: boolean;
  unknownReason?: PathUnknownReason;
  source: SourceSpan;
  provenance?: BashPathFactProvenance;
  globApproximation?: boolean;
};
