// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashListOperator } from "./BashListOperator.ts";
import type { BashPipeline } from "./BashPipeline.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashBlock = {
  pipeline: BashPipeline;
  operator?: BashListOperator;
  background?: boolean;
  span: SourceSpan;
};
