// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusExpectedLabel } from "./CorpusExpectedLabel.ts";
import type { DecisionEffect } from "./DecisionEffect.ts";
import type { ReplayReviewerOutcome } from "./ReplayReviewerOutcome.ts";

export type CapturedOutcome = {
  label: string;
  deterministicEffect?: DecisionEffect;
  reviewer?: ReplayReviewerOutcome;
  fixtureExpected?: CorpusExpectedLabel;
};
