// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandFamilyKey } from "./CommandFamilyKey.ts";
import type { CorpusSource } from "./CorpusSource.ts";
import type { CountByLabel } from "./CountByLabel.ts";

export type CommandFamilySummary = {
  family: CommandFamilyKey;
  calls: number;
  uniqueCommands: number;
  replayStatusCounts: ReadonlyArray<CountByLabel>;
  capturedOutcomeCounts: ReadonlyArray<CountByLabel>;
  modelReviewCalls: number;
  capturedDenialCalls: number;
  lowFidelityCalls: number;
  redactedCalls: number;
  sources: ReadonlyArray<CorpusSource>;
  sampleRecordIds: ReadonlyArray<string>;
  sampleCommands: ReadonlyArray<string>;
};
