// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PiBuiltinToolOperation } from "./PiBuiltinToolOperation.ts";

export type CommandFamilyKey = {
  id: string;
  toolName: string;
  kind: string;
  executable?: string;
  semanticArgument?: string;
  operation?: PiBuiltinToolOperation;
  operatorShape: ReadonlyArray<string>;
  hasSubstitution: boolean;
  hasStdoutRedirect: boolean;
  hasParseDiagnostics: boolean;
};
