// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommandFamilySummary } from "./CommandFamilySummary.ts";
import type { CorpusQuerySummary } from "./CorpusQuerySummary.ts";
import type { CorpusRecord } from "./CorpusRecord.ts";

export type CorpusQueryModel = {
  records: ReadonlyArray<CorpusRecord>;
  families: ReadonlyArray<CommandFamilySummary>;
  summary: CorpusQuerySummary;
  warnings: ReadonlyArray<string>;
};
