// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountByLabel } from "./CountByLabel.ts";

export type CorpusQuerySummary = {
  totalRecords: number;
  totalUniqueCommands: number;
  replayStatusCounts: ReadonlyArray<CountByLabel>;
  capturedOutcomeCounts: ReadonlyArray<CountByLabel>;
  sourceCounts: ReadonlyArray<CountByLabel>;
  modelReviewCalls: number;
  modelReviewUniqueCommands: number;
  lowFidelityCalls: number;
  redactedCalls: number;
  unmatchedAuditEntries: number;
};
