// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapturedOutcome } from "./CapturedOutcome.ts";
import type { CommandFamilyKey } from "./CommandFamilyKey.ts";
import type { ParsedEvidence } from "./ParsedEvidence.ts";
import type { ReplayedDecision } from "./ReplayedDecision.ts";
import type { SourceFidelity } from "./SourceFidelity.ts";
import type { ToolCallIdentity } from "./ToolCallIdentity.ts";

export type CorpusRecord = {
  id: string;
  identity: ToolCallIdentity;
  source: SourceFidelity;
  command: string;
  toolName: string;
  captured: CapturedOutcome;
  parsed: ParsedEvidence;
  replayed: ReplayedDecision;
  family: CommandFamilyKey;
  originalEntry: unknown;
};
