// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusExpectedLabel } from "./CorpusExpectedLabel.ts";
import type { CorpusFidelity } from "./CorpusFidelity.ts";
import type { CorpusSource } from "./CorpusSource.ts";
import type { DecisionEffect } from "./DecisionEffect.ts";
import type { ReplayReviewerOutcome } from "./ReplayReviewerOutcome.ts";

export type CorpusEntry = {
  command: string;
  toolName: string;
  toolInput?: unknown;
  toolCallId?: string;
  sessionId?: string;
  timestamp?: string;
  source: CorpusSource;
  sources: ReadonlyArray<CorpusSource>;
  provenance: string;
  deterministicOutcome?: DecisionEffect;
  reviewerOutcome?: ReplayReviewerOutcome;
  expectedLabel?: CorpusExpectedLabel;
  fidelity: CorpusFidelity;
};
