// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionSource } from "./DecisionSource.ts";

export type DecisionProvenance = {
  source: DecisionSource;
  packId?: string;
  ruleId?: string;
};
