// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoopVariableUnknownReason =
  | "opaque-iterator"
  | "iterator-mixed-unknown"
  | "outer-scope-variable";
