// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlockOperator } from "./BlockOperator.ts";
import type { CompositionOperator } from "./CompositionOperator.ts";
import type { CompoundForm } from "./CompoundForm.ts";
import type { MutationShapeKind } from "./MutationShapeKind.ts";
import type { MutationTrustBoundaryKind } from "./MutationTrustBoundaryKind.ts";
import type { PathFactsRequirement } from "./PathFactsRequirement.ts";
import type { PathScope } from "./PathScope.ts";
import type { PathScopeMatcherMode } from "./PathScopeMatcherMode.ts";
import type { PathUsageKind } from "./PathUsageKind.ts";
import type { PiFileMutationToolName } from "./PiFileMutationToolName.ts";
import type { RedirectStream } from "./RedirectStream.ts";
import type { RedirectTargetKind } from "./RedirectTargetKind.ts";

export type MatcherExpr =
  | { kind: "always" }
  | { kind: "tool"; tool: string }
  | { kind: "program"; name: string }
  | { kind: "arg0In"; values: ReadonlyArray<string> }
  | { kind: "argAt"; index: number; value: string }
  | { kind: "argCount"; min?: number; max?: number }
  | { kind: "envAssignmentCount"; min?: number; max?: number }
  | { kind: "argMatches"; index: number; pattern: string }
  | { kind: "flagPresent"; name: string }
  | {
      kind: "flagMatches";
      names?: ReadonlyArray<string>;
      prefixes?: ReadonlyArray<string>;
      shortChars?: ReadonlyArray<string>;
    }
  | {
      kind: "flagAllowlist";
      names?: ReadonlyArray<string>;
      shortChars?: ReadonlyArray<string>;
    }
  | {
      kind: "flagValueIn";
      names: ReadonlyArray<string>;
      values: ReadonlyArray<string>;
      allowUndefinedValue?: boolean;
    }
  | {
      kind: "flagCount";
      names?: ReadonlyArray<string>;
      shortChars?: ReadonlyArray<string>;
      max?: number;
      min?: number;
    }
  | { kind: "anyArgMatches"; pattern: string }
  | {
      kind: "envAssignmentNameIn";
      names?: ReadonlyArray<string>;
      prefixes?: ReadonlyArray<string>;
      caseInsensitivePrefixes?: ReadonlyArray<string>;
    }
  | { kind: "noSubstitution" }
  | { kind: "noStdoutRedirect" }
  | {
      kind: "redirect";
      stream?: RedirectStream;
      target?: string;
      targetKind?: RedirectTargetKind;
    }
  | { kind: "pipeline"; target: string }
  | { kind: "operator"; op: BlockOperator }
  | { kind: "stageEvery"; inner: MatcherExpr }
  | { kind: "stageSome"; inner: MatcherExpr }
  | { kind: "compoundForm"; form: CompoundForm }
  | { kind: "bodyStagesAllReadOnly" }
  | { kind: "bodyStagesAllScopeIn"; scopes: ReadonlyArray<PathScope> }
  | { kind: "iteratorScopesAllIn"; scopes: ReadonlyArray<PathScope> }
  | { kind: "noBodySubstitution" }
  | { kind: "noBodyShellWrap" }
  | { kind: "noBodyRedirectTo" }
  | { kind: "diagnosticCode"; code: string }
  | {
      kind: "composition";
      stage: MatcherExpr;
      operators: ReadonlyArray<CompositionOperator>;
      allowBackground?: boolean;
      minStages?: number;
      orFallback?: ReadonlyArray<string>;
    }
  | { kind: "all"; of: ReadonlyArray<MatcherExpr> }
  | { kind: "any"; of: ReadonlyArray<MatcherExpr> }
  | { kind: "not"; of: MatcherExpr }
  | { kind: "mutationTool"; tools: ReadonlyArray<PiFileMutationToolName> }
  | { kind: "mutationShape"; shape: MutationShapeKind }
  | {
      kind: "mutationTrustBoundary";
      in: ReadonlyArray<MutationTrustBoundaryKind>;
    }
  | {
      kind: "pathScope";
      mode: PathScopeMatcherMode;
      scopes: ReadonlyArray<PathScope>;
      programs?: ReadonlyArray<string>;
      usages?: ReadonlyArray<PathUsageKind>;
      allowExactPaths?: ReadonlyArray<string>;
      forbidPathSegments?: ReadonlyArray<string>;
      requireFacts?: PathFactsRequirement;
    };
