// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompileError } from "./CompileError.ts";
import type { PolicyPack } from "./PolicyPack.ts";

export type PackCompileResult = {
  pack?: PolicyPack;
  errors: ReadonlyArray<CompileError>;
};
