// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedShapeSummary } from "./ParsedShapeSummary.ts";
import type { ReplayPathFacts } from "./ReplayPathFacts.ts";
import type { ShapeDiagnostic } from "./ShapeDiagnostic.ts";
import type { ToolShape } from "./ToolShape.ts";

export type ParsedEvidence = {
  shape?: ToolShape;
  summary: ParsedShapeSummary;
  diagnostics: ReadonlyArray<ShapeDiagnostic>;
  pathFacts?: ReplayPathFacts;
};
