// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathUnknownReason =
  | "dynamic-expansion"
  | "glob-expansion"
  | "brace-expansion"
  | "unsupported-shell-literal"
  | "unsupported-shell-syntax"
  | "missing-operand"
  | "non-file-redirect"
  | "unresolved-cwd-prefix";
