// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PathScope =
  | "writable-project"
  | "project"
  | "temp"
  | "home"
  | "safe-home"
  | "sensitive-home"
  | "agent-support"
  | "system"
  | "outside"
  | "denied"
  | "unknown";
