// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathFactsRequirement } from "./PathFactsRequirement.ts";
import type { PathScope } from "./PathScope.ts";
import type { PathScopeMatcherMode } from "./PathScopeMatcherMode.ts";
import type { PathUsageKind } from "./PathUsageKind.ts";

export type PathScopeMatcherExpr = {
  kind: "pathScope";
  mode: PathScopeMatcherMode;
  scopes: ReadonlyArray<PathScope>;
  programs?: ReadonlyArray<string>;
  usages?: ReadonlyArray<PathUsageKind>;
  allowExactPaths?: ReadonlyArray<string>;
  forbidPathSegments?: ReadonlyArray<string>;
  requireFacts?: PathFactsRequirement;
};
