// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnknownPathBehavior } from "./UnknownPathBehavior.ts";

export type PathFactProjectScope = {
  roots: ReadonlyArray<string>;
  writableDirectories: ReadonlyArray<string>;
  tempDirectories: ReadonlyArray<string>;
  deniedDirectories: ReadonlyArray<string>;
  safeHomeDirectories: ReadonlyArray<string>;
  agentSupportDirectories?: ReadonlyArray<string>;
  unknownPathBehavior: UnknownPathBehavior;
};
