// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PiBuiltinToolOperation } from "./PiBuiltinToolOperation.ts";

export type PiBuiltinToolSpec = {
  toolName: string;
  operation: PiBuiltinToolOperation;
  pathKey?: string;
  pathOptional?: boolean;
};
