// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PiBuiltinToolOperation =
  | "read-file"
  | "list-directory"
  | "find-files"
  | "search-file-contents"
  | "status-read"
  | "state-read"
  | "workspace-search"
  | "interactive"
  | "mutation"
  | "agent-dispatch"
  | "network-read"
  | "embedded-shell";
