// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PiToolMutationFacts =
  | {
      kind: "edit";
      targetPath: string;
      editCount?: number;
      oldTextLength?: number;
      newTextLength?: number;
      replaceAll?: boolean;
      createsContent: boolean;
    }
  | {
      kind: "write";
      targetPath: string;
      contentLength?: number;
      overwrites: "unknown";
    };
