// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEffect } from "./DecisionEffect.ts";
import type { DecisionProvenance } from "./DecisionProvenance.ts";
import type { MatcherExpr } from "./MatcherExpr.ts";

export type PolicyRule = {
  id: string;
  effect: DecisionEffect;
  match: MatcherExpr;
  reason: string;
  provenance: DecisionProvenance;
};
