// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyPackDocLink } from "./PolicyPackDocLink.ts";
import type { PolicyPackExample } from "./PolicyPackExample.ts";
import type { PolicyPackWarning } from "./PolicyPackWarning.ts";

export type PolicyPackMetadata = {
  title?: string;
  description?: string;
  docs?: ReadonlyArray<PolicyPackDocLink>;
  tags?: ReadonlyArray<string>;
  warnings?: ReadonlyArray<PolicyPackWarning>;
  examples?: ReadonlyArray<PolicyPackExample>;
};
