// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEffect } from "./DecisionEffect.ts";

export type PolicyPackExample = {
  outcome: DecisionEffect;
  shape: string;
  note?: string;
};
