// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyPackMetadata } from "./PolicyPackMetadata.ts";
import type { PolicyRule } from "./PolicyRule.ts";

export type PolicyPack = {
  version: 1;
  id: string;
  metadata?: PolicyPackMetadata;
  rules: ReadonlyArray<PolicyRule>;
};
