// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalNotRunSeverity } from "./ProposalNotRunSeverity.ts";

export type ProposalNotRunReason = {
  code: string;
  message: string;
  severity: ProposalNotRunSeverity;
  details?: unknown;
};
