// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RedirectStream } from "./RedirectStream.ts";
import type { RedirectTargetKind } from "./RedirectTargetKind.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type Redirect = {
  stream: RedirectStream;
  targetKind: RedirectTargetKind;
  target: string;
  append: boolean;
  span: SourceSpan;
};
