// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Decision } from "./Decision.ts";
import type { DecisionProvenance } from "./DecisionProvenance.ts";
import type { ReplayStatus } from "./ReplayStatus.ts";

export type ReplayedDecision = {
  decision: Decision;
  status: ReplayStatus;
  provenance: DecisionProvenance;
  ruleId?: string;
};
