// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusQuerySummarySnapshot } from "./CorpusQuerySummarySnapshot.ts";
import type { ProposalNotRunReason } from "./ProposalNotRunReason.ts";
import type { ReplayDeltaBlockedSummary } from "./ReplayDeltaBlockedSummary.ts";
import type { ReplayDeltaChangedRecord } from "./ReplayDeltaChangedRecord.ts";
import type { ReplayDeltaFamily } from "./ReplayDeltaFamily.ts";
import type { ReplayDeltaImprovement } from "./ReplayDeltaImprovement.ts";
import type { ReplayDeltaRegression } from "./ReplayDeltaRegression.ts";
import type { ReplayDeltaStatus } from "./ReplayDeltaStatus.ts";
import type { ReplayDeltaTransitionCount } from "./ReplayDeltaTransitionCount.ts";

export type ReplayDelta = {
  version: number;
  status: ReplayDeltaStatus;
  notRun?: ProposalNotRunReason;
  baseline: CorpusQuerySummarySnapshot;
  candidate: CorpusQuerySummarySnapshot;
  changedCalls: number;
  changedUniqueCommands: number;
  transitions: ReadonlyArray<ReplayDeltaTransitionCount>;
  improvement: ReplayDeltaImprovement;
  blocked: ReplayDeltaBlockedSummary;
  regressions: ReadonlyArray<ReplayDeltaRegression>;
  changedFamilies: ReadonlyArray<ReplayDeltaFamily>;
  changedRecords: ReadonlyArray<ReplayDeltaChangedRecord>;
  warnings: ReadonlyArray<string>;
};
