// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplayDeltaBlockedSummary = {
  unknownToolCalls: number;
  unknownPathCalls: number | null;
  sealedFloorBlockCalls: number;
  activeDenyBlockCalls: number;
  lowFidelityCalls: number;
  redactedCalls: number;
};
