// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusFidelity } from "./CorpusFidelity.ts";
import type { ReplayStatus } from "./ReplayStatus.ts";

export type ReplayDeltaChangedRecord = {
  recordId: string;
  command: string;
  toolName: string;
  familyId: string;
  baselineStatus: ReplayStatus;
  candidateStatus: ReplayStatus;
  transition: string;
  baselineRuleId?: string;
  candidateRuleId?: string;
  baselineReason: string;
  candidateReason: string;
  fidelity: CorpusFidelity;
};
