// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusEntry } from "./CorpusEntry.ts";
import type { CountByLabel } from "./CountByLabel.ts";

export type ReplayCorpus = {
  entries: ReadonlyArray<CorpusEntry>;
  /**
   * JSON boundary uses arrays; the TS acquisition layer keeps its Map locally.
   */
  sourceSummary: ReadonlyArray<CountByLabel>;
  unmatchedAuditEntries: number;
  warnings: ReadonlyArray<string>;
};
