// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReplayStatus = "fast_path" | "review" | "hard_block";
