// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountByLabel } from "./CountByLabel.ts";
import type { ReplayDeltaRegression } from "./ReplayDeltaRegression.ts";
import type { ReplayDeltaTransitionCount } from "./ReplayDeltaTransitionCount.ts";

export type ReplayDeltaFamily = {
  familyId: string;
  toolName: string;
  executable?: string;
  calls: number;
  uniqueCommands: number;
  baselineStatusCounts: ReadonlyArray<CountByLabel>;
  candidateStatusCounts: ReadonlyArray<CountByLabel>;
  transitions: ReadonlyArray<ReplayDeltaTransitionCount>;
  reviewToAllowCalls: number;
  regressions: ReadonlyArray<ReplayDeltaRegression>;
  unchangedReviewCalls: number;
  sealedFloorBlockCalls: number;
  unknownToolCalls: number;
  unknownPathCalls: number | null;
  sampleRecordIds: ReadonlyArray<string>;
  sampleCommands: ReadonlyArray<string>;
};
