// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceSpan } from "./SourceSpan.ts";
import type { SubstitutionKind } from "./SubstitutionKind.ts";

export type Substitution = {
  kind: SubstitutionKind;
  raw: string;
  span: SourceSpan;
};
