// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashCommandShape } from "./BashCommandShape.ts";
import type { PiBuiltinToolShape } from "./PiBuiltinToolShape.ts";
import type { UnknownToolShape } from "./UnknownToolShape.ts";

export type ToolShape =
  | BashCommandShape
  | PiBuiltinToolShape
  | UnknownToolShape;
