// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolPathFact } from "./ToolPathFact.ts";

export type ToolPathFacts = {
  baseCwd: string;
  effectiveCwd: string;
  facts: ReadonlyArray<ToolPathFact>;
  hasUnknown: boolean;
  hasDenied: boolean;
  hasOutsideProject: boolean;
  hasSystemPath: boolean;
};
