// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathNormalization } from "./PathNormalization.ts";
import type { PathScope } from "./PathScope.ts";
import type { PathUnknownReason } from "./PathUnknownReason.ts";
import type { ToolPathAccess } from "./ToolPathAccess.ts";
import type { ToolPathUsage } from "./ToolPathUsage.ts";

export type ToolPathFact = {
  id: string;
  toolName?: string;
  usage: ToolPathUsage;
  access: ToolPathAccess;
  raw: string;
  literal?: string;
  absolutePath?: string;
  scope: PathScope;
  matchedScopes: ReadonlyArray<PathScope>;
  normalization: PathNormalization;
  isAbsolute: boolean;
  isRelative: boolean;
  hasParentTraversal: boolean;
  dynamic: boolean;
  unknownReason?: PathUnknownReason;
};
