// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShapeDiagnostic } from "./ShapeDiagnostic.ts";

export type UnknownToolShape = {
  kind: "unknown";
  toolName: string;
  rawInput: unknown;
  diagnostics: ReadonlyArray<ShapeDiagnostic>;
};
