import { execFileSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const contractsDirectory = join(root, "src", "contracts");
const generatedHeader =
  "// @generated by ts-rs; do not edit. Run `npm run contracts:generate`.\n";

function runGenerator(outputDirectory: string): void {
  execFileSync(
    "cargo",
    [
      "run",
      "--quiet",
      "-p",
      "clearance-core",
      "--bin",
      "export-contracts",
      "--",
      outputDirectory,
    ],
    { cwd: root, stdio: "inherit" },
  );

  const generatedFiles = readdirSync(outputDirectory)
    .filter((file) => file.endsWith(".ts"))
    .map((file) => join(outputDirectory, file));
  if (generatedFiles.length > 0) {
    execFileSync(
      "npx",
      ["exec", "biome", "format", "--write", ...generatedFiles],
      {
        cwd: root,
        stdio: "inherit",
      },
    );
  }

  for (const file of generatedFiles) {
    const contents = readFileSync(file, "utf8").replaceAll(
      "Array<",
      "ReadonlyArray<",
    );
    writeFileSync(file, generatedHeader + contents, "utf8");
  }

  const files = readdirSync(outputDirectory)
    .filter((file) => file.endsWith(".ts"))
    .sort();
  const index = [
    generatedHeader.trimEnd(),
    ...files.map((file) => `export * from "./${file}";`),
    "",
  ].join("\n");
  writeFileSync(join(outputDirectory, "index.ts"), index, "utf8");

  execFileSync(
    "npx",
    [
      "exec",
      "biome",
      "check",
      "--write",
      ...readdirSync(outputDirectory).map((file) =>
        join(outputDirectory, file),
      ),
    ],
    { cwd: root, stdio: "inherit" },
  );
}

function snapshot(directory: string): Map<string, string> {
  const files = readdirSync(directory).filter((file) => file.endsWith(".ts"));
  return new Map(
    files.map((file) => [file, readFileSync(join(directory, file), "utf8")]),
  );
}

function check(): void {
  const temporaryDirectory = mkdtempSync(
    join(tmpdir(), "pi-clearance-contracts-"),
  );
  try {
    runGenerator(temporaryDirectory);
    const expected = snapshot(temporaryDirectory);
    const actual = existsSync(contractsDirectory)
      ? snapshot(contractsDirectory)
      : new Map<string, string>();
    const differences: string[] = [];

    for (const file of new Set([...expected.keys(), ...actual.keys()])) {
      if (expected.get(file) !== actual.get(file)) {
        differences.push(relative(root, join("src", "contracts", file)));
      }
    }

    if (differences.length > 0) {
      console.error(
        `Generated contract drift detected in:\n${differences
          .sort()
          .map((file) => `  - ${file}`)
          .join("\n")}\nRun pnpm contracts:generate and commit the result.`,
      );
      process.exitCode = 1;
    }
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true });
  }
}

function generate(): void {
  const temporaryDirectory = mkdtempSync(
    join(tmpdir(), "pi-clearance-contracts-"),
  );
  try {
    runGenerator(temporaryDirectory);
    rmSync(contractsDirectory, { recursive: true, force: true });
    mkdirSync(contractsDirectory, { recursive: true });
    const generated = snapshot(temporaryDirectory);
    for (const [file, contents] of generated) {
      writeFileSync(join(contractsDirectory, file), contents, "utf8");
    }
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true });
  }
}

const command = process.argv[2];
if (command === "check") {
  check();
} else if (command === "generate") {
  generate();
} else {
  console.error("Usage: tsx scripts/contracts.ts <generate|check>");
  process.exitCode = 2;
}
