// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashIteratorEntryKind } from "./BashIteratorEntryKind.ts";
import type { QuoteKind } from "./QuoteKind.ts";
import type { SourceSpan } from "./SourceSpan.ts";

export type BashIteratorEntry = {
  kind: BashIteratorEntryKind;
  raw: string;
  literal: string;
  quote: QuoteKind;
  span: SourceSpan;
};
