// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceSpan } from "./SourceSpan.ts";

export type BashFlag = {
  raw: string;
  name: string;
  short: boolean;
  value?: string;
  span: SourceSpan;
};
