// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashBlock } from "./BashBlock.ts";
import type { BashPathFacts } from "./BashPathFacts.ts";
import type { BashStage } from "./BashStage.ts";
import type { ShapeDiagnostic } from "./ShapeDiagnostic.ts";

export type BashCommandShape = {
  kind: "bash";
  rawCommand: string;
  cwdPrefix?: string;
  blocks: ReadonlyArray<BashBlock>;
  stages: ReadonlyArray<BashStage>;
  diagnostics: ReadonlyArray<ShapeDiagnostic>;
  pathFacts?: BashPathFacts;
};
