// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashPathFact } from "./BashPathFact.ts";

export type BashPathFacts = {
  baseCwd: string;
  effectiveCwd: string;
  cwdPrefix?: BashPathFact;
  facts: ReadonlyArray<BashPathFact>;
  hasUnknown: boolean;
  hasDenied: boolean;
  hasOutsideProject: boolean;
  hasSystemPath: boolean;
};
