// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PiBuiltinToolOperation } from "./PiBuiltinToolOperation.ts";

export type ParsedShapeSummary = {
  toolKind: string;
  primaryExecutable?: string;
  toolOperation?: PiBuiltinToolOperation;
  arguments: ReadonlyArray<string>;
  flags: ReadonlyArray<string>;
  operatorShape: ReadonlyArray<string>;
  hasSubstitution: boolean;
  hasStdoutRedirect: boolean;
  diagnosticCodes: ReadonlyArray<string>;
  parseError?: string;
};
