// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbeddedShellProjection } from "./EmbeddedShellProjection.ts";
import type { MutationTrustBoundaryClassification } from "./MutationTrustBoundaryClassification.ts";
import type { PiBuiltinToolOperation } from "./PiBuiltinToolOperation.ts";
import type { PiBuiltinToolPathInput } from "./PiBuiltinToolPathInput.ts";
import type { PiToolMutationFacts } from "./PiToolMutationFacts.ts";
import type { ShapeDiagnostic } from "./ShapeDiagnostic.ts";
import type { ToolPathFacts } from "./ToolPathFacts.ts";

export type PiBuiltinToolShape = {
  kind: "pi-tool";
  toolName: string;
  operation: PiBuiltinToolOperation;
  rawInput: unknown;
  pathInputs: ReadonlyArray<PiBuiltinToolPathInput>;
  diagnostics: ReadonlyArray<ShapeDiagnostic>;
  embeddedShell?: EmbeddedShellProjection;
  mutationFacts?: PiToolMutationFacts;
  trustBoundary?: MutationTrustBoundaryClassification;
  pathFacts?: ToolPathFacts;
};
