// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BashPathFacts } from "./BashPathFacts.ts";
import type { ToolPathFacts } from "./ToolPathFacts.ts";

export type ReplayPathFacts = BashPathFacts | ToolPathFacts;
