// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisionEffect } from "./DecisionEffect.ts";
import type { ReplayReviewerMode } from "./ReplayReviewerMode.ts";

export type ReplayReviewerOutcome = {
  mode: ReplayReviewerMode;
  finalEffect: DecisionEffect;
};
