// @generated by ts-rs; do not edit. Run `pnpm contracts:generate`.
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorpusFidelity } from "./CorpusFidelity.ts";
import type { CorpusSource } from "./CorpusSource.ts";

export type SourceFidelity = {
  source: CorpusSource;
  sources: ReadonlyArray<CorpusSource>;
  provenance: string;
  fidelity: CorpusFidelity;
  redacted: boolean;
  lowFidelityReasons: ReadonlyArray<string>;
};
